version: '3'

services:
  web:
    image: node:14
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"

  db:
    image: mongo
    ports:
      - "27071:27071"